-- DLS 2026 Gaming Hub - Complete Database Schema
-- This file contains all migrations combined
-- Paste this into Supabase SQL Editor and execute

-- ============================================================
-- Migration 1: 20260526181245 - Base Tables
-- ============================================================
CREATE TABLE IF NOT EXISTS user_roles (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  user_id UUID NOT NULL REFERENCES auth.users (id),
  role TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  username TEXT UNIQUE,
  full_name TEXT,
  phone TEXT,
  avatar_url TEXT,
  bio TEXT,
  wins INT DEFAULT 0,
  losses INT DEFAULT 0,
  rating DECIMAL DEFAULT 1000,
  updated_at TIMESTAMP DEFAULT NOW()
);

-- ============================================================
-- Migration 2: 20260526181257 - Tournaments
-- ============================================================
CREATE TABLE IF NOT EXISTS tournaments (
  id UUID PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'pending',
  prize_amount DECIMAL,
  max_players INT,
  start_date TIMESTAMP,
  end_date TIMESTAMP,
  created_by UUID REFERENCES auth.users (id),
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tournament_participants (
  id UUID PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tournament_id UUID REFERENCES tournaments (id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users (id) ON DELETE CASCADE,
  status TEXT DEFAULT 'active',
  joined_at TIMESTAMP DEFAULT NOW()
);

-- ============================================================
-- Migration 3: 20260601102444 - Live Matches & Signaling
-- ============================================================
CREATE TABLE IF NOT EXISTS live_matches (
  id UUID PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  host_id UUID NOT NULL REFERENCES auth.users (id),
  join_code TEXT UNIQUE NOT NULL,
  home_player TEXT,
  away_player TEXT,
  home_score INT DEFAULT 0,
  away_score INT DEFAULT 0,
  status TEXT DEFAULT 'live',
  started_at TIMESTAMP DEFAULT NOW(),
  ended_at TIMESTAMP,
  recording_url TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS live_signaling (
  id UUID PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  match_id UUID REFERENCES live_matches (id) ON DELETE CASCADE,
  from_user UUID REFERENCES auth.users (id),
  to_user UUID REFERENCES auth.users (id),
  kind TEXT,
  payload JSONB,
  created_at TIMESTAMP DEFAULT NOW()
);

-- ============================================================
-- Migration 4: 20260601103140 - Live Chat
-- ============================================================
CREATE TABLE IF NOT EXISTS live_chat (
  id UUID PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  match_id UUID REFERENCES live_matches (id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users (id),
  username TEXT NOT NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- ============================================================
-- Migration 5: 20260601103202 - Direct Messages
-- ============================================================
CREATE TABLE IF NOT EXISTS dm_threads (
  id UUID PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_a_id UUID NOT NULL REFERENCES auth.users (id),
  user_b_id UUID NOT NULL REFERENCES auth.users (id),
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS dm_messages (
  id UUID PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  thread_id UUID REFERENCES dm_threads (id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users (id),
  body TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- ============================================================
-- Migration 6: 20260602074306 - Indexes & Optimizations
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_profiles_username ON profiles(username);
CREATE INDEX IF NOT EXISTS idx_tournaments_status ON tournaments(status);
CREATE INDEX IF NOT EXISTS idx_tournaments_created_by ON tournaments(created_by);
CREATE INDEX IF NOT EXISTS idx_tournament_participants_user ON tournament_participants(user_id);
CREATE INDEX IF NOT EXISTS idx_tournament_participants_tournament ON tournament_participants(tournament_id);
CREATE INDEX IF NOT EXISTS idx_live_matches_host ON live_matches(host_id);
CREATE INDEX IF NOT EXISTS idx_live_matches_status ON live_matches(status);
CREATE INDEX IF NOT EXISTS idx_live_matches_join_code ON live_matches(join_code);
CREATE INDEX IF NOT EXISTS idx_live_signaling_match ON live_signaling(match_id);
CREATE INDEX IF NOT EXISTS idx_live_chat_match ON live_chat(match_id);
CREATE INDEX IF NOT EXISTS idx_live_chat_user ON live_chat(user_id);
CREATE INDEX IF NOT EXISTS idx_dm_threads_users ON dm_threads(user_a_id, user_b_id);
CREATE INDEX IF NOT EXISTS idx_dm_messages_thread ON dm_messages(thread_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_user ON user_roles(user_id);

-- ============================================================
-- Migration 7: 20260604184744 - RLS Policies
-- ============================================================
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE tournaments ENABLE ROW LEVEL SECURITY;
ALTER TABLE tournament_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE live_matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE live_signaling ENABLE ROW LEVEL SECURITY;
ALTER TABLE live_chat ENABLE ROW LEVEL SECURITY;
ALTER TABLE dm_threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE dm_messages ENABLE ROW LEVEL SECURITY;

-- Profiles policies
CREATE POLICY "Profiles are viewable by everyone" ON profiles
  FOR SELECT USING (true);

CREATE POLICY "Users can update own profile" ON profiles
  FOR UPDATE USING (auth.uid() = id);

-- Tournaments policies
CREATE POLICY "Tournaments are viewable by everyone" ON tournaments
  FOR SELECT USING (true);

CREATE POLICY "Users can create tournaments" ON tournaments
  FOR INSERT WITH CHECK (auth.uid() = created_by);

CREATE POLICY "Tournament creators can update their tournaments" ON tournaments
  FOR UPDATE USING (auth.uid() = created_by);

-- Live matches policies
CREATE POLICY "Live matches are viewable by everyone" ON live_matches
  FOR SELECT USING (true);

CREATE POLICY "Users can create live matches" ON live_matches
  FOR INSERT WITH CHECK (auth.uid() = host_id);

CREATE POLICY "Match hosts can update their matches" ON live_matches
  FOR UPDATE USING (auth.uid() = host_id);

-- Live signaling policies
CREATE POLICY "Users can view signaling for their matches" ON live_signaling
  FOR SELECT USING (
    auth.uid() = from_user OR 
    auth.uid() = to_user OR
    auth.uid() IN (
      SELECT host_id FROM live_matches WHERE id = match_id
    )
  );

CREATE POLICY "Users can insert signaling messages" ON live_signaling
  FOR INSERT WITH CHECK (auth.uid() = from_user);

-- Live chat policies
CREATE POLICY "Live chat is viewable by everyone" ON live_chat
  FOR SELECT USING (true);

CREATE POLICY "Users can insert chat messages" ON live_chat
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Direct messages policies
CREATE POLICY "Users can view their DM threads" ON dm_threads
  FOR SELECT USING (auth.uid() = user_a_id OR auth.uid() = user_b_id);

CREATE POLICY "Users can view their DM messages" ON dm_messages
  FOR SELECT USING (
    auth.uid() IN (
      SELECT user_a_id FROM dm_threads WHERE id = thread_id
      UNION
      SELECT user_b_id FROM dm_threads WHERE id = thread_id
    )
  );

CREATE POLICY "Users can insert DM messages" ON dm_messages
  FOR INSERT WITH CHECK (
    auth.uid() IN (
      SELECT user_a_id FROM dm_threads WHERE id = thread_id
      UNION
      SELECT user_b_id FROM dm_threads WHERE id = thread_id
    )
  );

-- ============================================================
-- Migration 8: 20260604185630 - Recording Support
-- ============================================================
ALTER TABLE live_matches ADD COLUMN IF NOT EXISTS recording_url TEXT;

-- ============================================================
-- Migration 9: 20260606 - Storage Bucket Creation
-- ============================================================
-- Note: Storage buckets must be created via Storage UI or API
-- Required buckets:
-- 1. match-recordings (Private) - for recorded match videos
-- 2. avatars (Public) - for player profile pictures
-- 3. tournament-covers (Public) - for tournament header images

-- ============================================================
-- END OF MIGRATIONS
-- ============================================================
-- After running this SQL, create the storage buckets:
-- 1. Go to Storage tab in Supabase Dashboard
-- 2. Click "New Bucket"
-- 3. Create buckets as listed above
-- ============================================================
