// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use import.meta.env for client-side (Vite build-time replacement)
// Fall back to process.env for SSR (server-side rendering)
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

function createSupabaseClient() {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Using a safe stub.`;
    console.warn(`[Supabase] ${message}`);

    // Return a safe stub that implements the minimal supabase API used server-side.
    const stub: any = {};
    stub.auth = {
      getSession: async () => ({ data: { session: null } }),
      // client-side methods may be called in browser; return a harmless rejection/object
      signInWithPassword: async () => ({ error: { message: 'Supabase not configured' } }),
      onAuthStateChange: (_callback: any) => ({
        data: {
          subscription: {
            unsubscribe: () => {},
          },
        },
      }),
    };

    // Minimal query builder that supports chaining used in the codebase: select().eq().order().limit().then(cb)
    const makeQuery = () => {
      const q: any = {};
      q._chain = [];
      q.select = (..._args: any[]) => q;
      q.eq = (_col: string, _val: any) => q;
      q.order = (_col: string, _opts: any) => q;
      q.limit = (_n: number) => q;
      q.update = async (_data: any) => ({ error: null });
      q.insert = async (_data: any) => ({ error: null });
      q.delete = async () => ({ error: null });
      q.then = (cb: any) => Promise.resolve(cb({ data: [] }));
      return q;
    };

    stub.from = (_table: string) => makeQuery();

    // Real-time channel stub (client-only in practice)
    stub.channel = (_name: string) => ({
      on: () => ({ subscribe: async () => ({}) }),
      subscribe: async () => ({}),
    });
    stub.removeChannel = async (_ch: any) => {};

    return stub as ReturnType<typeof createClient>;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase as any, prop as any, receiver);
  },
});

